# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Github Action Demo

on:
  push:
    branches: [ master, dev ]

jobs:
  demo-deployment:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        MY_FOO: foo
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -v
    - run: node demo.js
    - name: test my env
      run: echo "my foo is <$MY_FOO>"
